//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Mobile_ { get; set; }
        public string Address { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
